import { NextResponse } from "next/server";
import { db } from "@/db";
import { applications } from "@/db/schema";
import { eq } from "drizzle-orm";

const SAMPLE_APPLICATIONS = [
  {
    applicationNumber: "VTC-GHR-2025-1082",
    fullName: "أحمد محمد محمود الفاعوري",
    nationality: "أردني",
    nationalId: "2006123456",
    birthDate: "2006-05-14",
    age: 18,
    gender: "ذكر",
    birthPlace: "داخل المملكة",
    isAidBeneficiary: true,
    phoneNumber: "0798123456",
    whatsappNumber: "0798123456",
    emergencyPhone: "0778123456",
    governorate: "البلقاء",
    district: "الغور الأوسط - دير علا",
    detailedAddress: "دير علا - الحي الغربي بجانب مدرسة البنين",
    iban: "JO94ARBK00000001234567890123",
    guarantorName: null,
    guarantorPhone: null,
    educationLevel: "إنهاء الصف العاشر الأساسي",
    schoolName: "مدرسة دير علا الثانوية للبنين",
    graduationYear: "2024",
    isPhysicallyFit: true,
    primarySpecialization: "الطاقة الشمسية",
    secondarySpecialization: "كهرباء مركبات",
    motivation: "أرغب بدخول مجال الطاقة المتجددة نظراً لتوفر المشاريع الزراعية والشمسية في منطقة وادي الأردن والحاجة لمهندسين وفنيين أكفاء.",
    status: "مقبول نهائياً",
    interviewDate: "2025-08-15 الساعة 10:00 صباحاً - القاعة الرئيسية",
    supervisorNotes: "تم اجتياز المقابلة وفحص اللياقة بنجاح. ملفه مكتمل وهو مستفيد من صندوق المعونة الوطنية.",
    documentsSubmitted: JSON.stringify(["هوية الأحوال المدنية", "شهادة الصف العاشر", "صور شخصية", "دفتر العائلة", "رقم الحساب البنكي (IBAN)"]),
  },
  {
    applicationNumber: "VTC-GHR-2025-2144",
    fullName: "عمر خالد إبراهيم العدوان",
    nationality: "أردني",
    nationalId: "2007654321",
    birthDate: "2007-09-22",
    age: 17,
    gender: "ذكر",
    birthPlace: "داخل المملكة",
    isAidBeneficiary: false,
    phoneNumber: "0775544332",
    whatsappNumber: "0775544332",
    emergencyPhone: "0785544332",
    governorate: "البلقاء",
    district: "الغور الأوسط - الشونة الجنوبية",
    detailedAddress: "الشونة الجنوبية - بالقرب من المركز الصحي",
    iban: "JO55CBJO00000009876543210123",
    guarantorName: null,
    guarantorPhone: null,
    educationLevel: "أول ثانوي مهني",
    schoolName: "مدرسة الشونة المهنية",
    graduationYear: "2024",
    isPhysicallyFit: true,
    primarySpecialization: "ميكانيك مركبات",
    secondarySpecialization: "كهرباء مركبات",
    motivation: "شغف كبير بصيانة محركات السيارات والآليات الزراعية ومعدات النقل.",
    status: "بانتظار المقابلة",
    interviewDate: "2025-08-20 الساعة 09:30 صباحاً - مشغل الميكانيك",
    supervisorNotes: "تم تدقيق الوثائق مبدئياً وتحديد موعد المقابلة العملية.",
    documentsSubmitted: JSON.stringify(["هوية الأحوال المدنية", "شهادة الصف العاشر", "صور شخصية", "دفتر العائلة"]),
  },
  {
    applicationNumber: "VTC-GHR-2025-3390",
    fullName: "طارق زياد خليل العبادي",
    nationality: "أردني",
    nationalId: "2005987612",
    birthDate: "2005-11-03",
    age: 19,
    gender: "ذكر",
    birthPlace: "داخل المملكة",
    isAidBeneficiary: true,
    phoneNumber: "0789988776",
    whatsappNumber: "0789988776",
    emergencyPhone: "0799988776",
    governorate: "البلقاء",
    district: "الغور الأوسط - الكرامة",
    detailedAddress: "بلدة الكرامة - الشارع الرئيسي",
    iban: "JO12JIBA00000004561237890123",
    guarantorName: null,
    guarantorPhone: null,
    educationLevel: "إنهاء الصف العاشر الأساسي",
    schoolName: "مدرسة الكرامة الثانوية للبنين",
    graduationYear: "2023",
    isPhysicallyFit: true,
    primarySpecialization: "كهرباء مركبات",
    secondarySpecialization: "ميكانيك مركبات",
    motivation: "التدرب على فحص وبرمجة كمبيوتر السيارات والأنظمة الكهربائية والهايبرد.",
    status: "مقبول مبدئياً",
    interviewDate: "تمت المقابلة بنجاح - تسليم باقي المستندات",
    supervisorNotes: "أظهر كفاءة ممتازة في الفحص النظري، مستحق لبدل المواصلات الشهري.",
    documentsSubmitted: JSON.stringify(["هوية الأحوال المدنية", "شهادة الصف العاشر", "دفتر العائلة"]),
  },
  {
    applicationNumber: "VTC-GHR-2025-4512",
    fullName: "حمزة رياض عبد الله الشطي",
    nationality: "أردني",
    nationalId: "2008112233",
    birthDate: "2008-01-18",
    age: 16,
    gender: "ذكر",
    birthPlace: "داخل المملكة",
    isAidBeneficiary: false,
    phoneNumber: "0791238899",
    whatsappNumber: "0791238899",
    emergencyPhone: "0771238899",
    governorate: "البلقاء",
    district: "الغور الأوسط - معدي",
    detailedAddress: "بلدة معدي - قرب البلدية",
    iban: null,
    guarantorName: null,
    guarantorPhone: null,
    educationLevel: "إنهاء الصف العاشر الأساسي",
    schoolName: "مدرسة معدي الأساسية للبنين",
    graduationYear: "2024",
    isPhysicallyFit: true,
    primarySpecialization: "تكييف وتبريد",
    secondarySpecialization: "الطاقة الشمسية",
    motivation: "التخصص مطلوب جداً في الأغوار بسبب ارتفاع درجات الحرارة واحتياج المزارع والمنازل والمبردات لصيانة دورية.",
    status: "قيد المراجعة",
    interviewDate: "سيتم التحديد بعد استكمال الوثائق",
    supervisorNotes: "الطلب جديد ويحتاج إرفاق صور شخصية وتأكيد رقم الآيبان إن وجد.",
    documentsSubmitted: JSON.stringify(["هوية الأحوال المدنية", "شهادة الصف العاشر"]),
  },
  {
    applicationNumber: "VTC-GHR-2025-5689",
    fullName: "سيف الدين ناصر محمد الغنانيم",
    nationality: "أردني",
    nationalId: "2006334455",
    birthDate: "2006-08-10",
    age: 18,
    gender: "ذكر",
    birthPlace: "داخل المملكة",
    isAidBeneficiary: true,
    phoneNumber: "0787766554",
    whatsappNumber: "0787766554",
    emergencyPhone: "0797766554",
    governorate: "البلقاء",
    district: "الغور الأوسط - الروضة",
    detailedAddress: "منطقة الروضة - الحي الشرقي",
    iban: "JO88THBK00000003322114455667",
    guarantorName: null,
    guarantorPhone: null,
    educationLevel: "إنهاء الصف العاشر الأساسي",
    schoolName: "مدرسة الروضة الثانوية",
    graduationYear: "2023",
    isPhysicallyFit: true,
    primarySpecialization: "دهان مركبات",
    secondarySpecialization: "ميكانيك مركبات",
    motivation: "تعلم تقنيات الدهان الحديثة وأفران التجفيف ومعالجة هياكل السيارات لتأسيس ورشة عمل خاصة.",
    status: "مقبول نهائياً",
    interviewDate: "تم الانتهاء والتثبيت للعام التدريبي الجديد",
    supervisorNotes: "تم تسليم جميع الأوراق وحجز المقعد وتوزيع زي التدريب المهني والسلامة العامة.",
    documentsSubmitted: JSON.stringify(["هوية الأحوال المدنية", "شهادة الصف العاشر", "صور شخصية", "دفتر العائلة", "شهادة اللياقة الطبية", "رقم الحساب البنكي (IBAN)"]),
  },
  {
    applicationNumber: "VTC-GHR-2025-6721",
    fullName: "مصطفى يوسف أحمد عبد المنعم",
    nationality: "غير أردني",
    nationalId: "EG99283741",
    birthDate: "2006-03-25",
    age: 18,
    gender: "ذكر",
    birthPlace: "خارج المملكة",
    isAidBeneficiary: false,
    phoneNumber: "0796655441",
    whatsappNumber: "0796655441",
    emergencyPhone: "0786655441",
    governorate: "البلقاء",
    district: "الغور الأوسط - دير علا",
    detailedAddress: "دير علا - مجمع المزارع المركزي",
    iban: null,
    guarantorName: "خالد عبد الفتاح العبادي",
    guarantorPhone: "0772211009",
    educationLevel: "إنهاء الصف العاشر الأساسي",
    schoolName: "مدرسة مصدقة من وزارة التربية والتعليم",
    graduationYear: "2023",
    isPhysicallyFit: true,
    primarySpecialization: "الطاقة الشمسية",
    secondarySpecialization: "تكييف وتبريد",
    motivation: "الحصول على شهادة مهنية معتمدة من مؤسسة التدريب المهني في تركيب المضخات والأنظمة الكهروضوئية.",
    status: "بانتظار المقابلة",
    interviewDate: "2025-08-22 الساعة 11:00 صباحاً",
    supervisorNotes: "تم إحضار الإقامة السارية وتوقيع الكفيل، بانتظار المقابلة الشخصية.",
    documentsSubmitted: JSON.stringify(["صورة جواز السفر", "صورة الإقامة السارية", "شهادة العاشر المصدقة", "صور شخصية", "بيانات الكفيل"]),
  }
];

export async function POST() {
  try {
    const existing = await db.select().from(applications).limit(1);
    if (existing.length > 0) {
      // Even if data exists, ensure we have at least one female "Data Entry" record
      const hasFemale = await db
        .select()
        .from(applications)
        .where(eq(applications.gender, "أنثى"))
        .limit(1);
      if (hasFemale.length === 0) {
        const femaleRecord = {
          applicationNumber: "VTC-GHR-2025-7301",
          fullName: "رانيا محمود سليم الزعبي",
          nationality: "أردني",
          nationalId: "2007456789",
          birthDate: "2007-06-12",
          age: 17,
          gender: "أنثى",
          birthPlace: "داخل المملكة",
          isAidBeneficiary: false,
          phoneNumber: "0794455667",
          whatsappNumber: "0794455667",
          emergencyPhone: "0784455667",
          governorate: "البلقاء",
          district: "الغور الأوسط - الشونة الجنوبية",
          detailedAddress: "الشونة الجنوبية - قرب مدرسة البنات",
          iban: "JO77ARBK00000008877665544332",
          guarantorName: null,
          guarantorPhone: null,
          educationLevel: "إنهاء الصف العاشر الأساسي",
          schoolName: "مدرسة الشونة الثانوية للبنات",
          graduationYear: "2024",
          isPhysicallyFit: true,
          primarySpecialization: "مدخل بيانات",
          secondarySpecialization: "تكييف وتبريد",
          motivation: "الرغبة في تعلم إدخال البيانات والمهارات المكتبية لدخول سوق العمل بسرعة.",
          status: "بانتظار المقابلة",
          interviewDate: "2025-08-21 الساعة 11:00 صباحاً - مختبر الحاسوب",
          supervisorNotes: "دورة مخصصة للإناث فقط. الملف مكتمل ومستحق لبدل المواصلات.",
          documentsSubmitted: JSON.stringify([
            "هوية الأحوال المدنية",
            "شهادة الصف العاشر",
            "صور شخصية",
            "دفتر العائلة",
            "رقم الحساب البنكي (IBAN)",
          ]),
        };
        await db.insert(applications).values(femaleRecord);
        return NextResponse.json({
          success: true,
          message: "تمت إضافة متدربة جديدة لدورة مدخل بيانات (إناث فقط)",
          count: 1,
        });
      }
      return NextResponse.json({
        success: true,
        message: "قاعدة البيانات تحتوي بالفعل على طلبات مسجلة",
      });
    }

    const femaleSample = {
      applicationNumber: "VTC-GHR-2025-7301",
      fullName: "رانيا محمود سليم الزعبي",
      nationality: "أردني",
      nationalId: "2007456789",
      birthDate: "2007-06-12",
      age: 17,
      gender: "أنثى",
      birthPlace: "داخل المملكة",
      isAidBeneficiary: false,
      phoneNumber: "0794455667",
      whatsappNumber: "0794455667",
      emergencyPhone: "0784455667",
      governorate: "البلقاء",
      district: "الغور الأوسط - الشونة الجنوبية",
      detailedAddress: "الشونة الجنوبية - قرب مدرسة البنات",
      iban: "JO77ARBK00000008877665544332",
      guarantorName: null,
      guarantorPhone: null,
      educationLevel: "إنهاء الصف العاشر الأساسي",
      schoolName: "مدرسة الشونة الثانوية للبنات",
      graduationYear: "2024",
      isPhysicallyFit: true,
      primarySpecialization: "مدخل بيانات",
      secondarySpecialization: "تكييف وتبريد",
      motivation: "الرغبة في تعلم إدخال البيانات والمهارات المكتبية لدخول سوق العمل بسرعة.",
      status: "بانتظار المقابلة",
      interviewDate: "2025-08-21 الساعة 11:00 صباحاً - مختبر الحاسوب",
      supervisorNotes: "دورة مخصصة للإناث فقط. الملف مكتمل ومستحق لبدل المواصلات.",
      documentsSubmitted: JSON.stringify([
        "هوية الأحوال المدنية",
        "شهادة الصف العاشر",
        "صور شخصية",
        "دفتر العائلة",
        "رقم الحساب البنكي (IBAN)",
      ]),
    };

    for (const app of [...SAMPLE_APPLICATIONS, femaleSample]) {
      await db.insert(applications).values(app);
    }

    return NextResponse.json({
      success: true,
      message: "تم تهيئة البيانات التجريبية بنجاح لمعهد الغور الأوسط",
      count: SAMPLE_APPLICATIONS.length + 1,
    });
  } catch (error) {
    console.error("Seeding error:", error);
    return NextResponse.json(
      { success: false, error: "تعذر إدخال البيانات التجريبية" },
      { status: 500 }
    );
  }
}
